# ARM32 Windows toolchain for the OpenAL Soft probe/build.
set(CMAKE_SYSTEM_NAME Windows CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_VERSION 10.0.19041.0 CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_PROCESSOR ARM CACHE STRING "" FORCE)

set(ARM_MSVC_ROOT "D:/Visual Studio 2026/VC/Tools/MSVC/14.44.35207")
set(ARM_SDK_ROOT "D:/WindowsSDK")
set(ARM_SDK_VERSION "10.0.19041.0")

set(CMAKE_C_COMPILER "${ARM_MSVC_ROOT}/bin/HostX86/arm/cl.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${ARM_MSVC_ROOT}/bin/HostX86/arm/cl.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "${ARM_MSVC_ROOT}/bin/HostX86/arm/link.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${ARM_MSVC_ROOT}/bin/HostX86/arm/lib.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER "${ARM_SDK_ROOT}/bin/${ARM_SDK_VERSION}/x86/rc.exe" CACHE FILEPATH "" FORCE)

set(CMAKE_C_FLAGS_INIT "/DWIN32 /D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1")
set(CMAKE_CXX_FLAGS_INIT "/DWIN32 /D_ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1")
set(CMAKE_EXE_LINKER_FLAGS_INIT "/MACHINE:ARM")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "/MACHINE:ARM")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded" CACHE STRING "" FORCE)

set(CMAKE_SYSTEM_INCLUDE_PATH
    "${ARM_MSVC_ROOT}/include"
    "${ARM_SDK_ROOT}/Include/${ARM_SDK_VERSION}/ucrt"
    "${ARM_SDK_ROOT}/Include/${ARM_SDK_VERSION}/shared"
    "${ARM_SDK_ROOT}/Include/${ARM_SDK_VERSION}/um")
set(CMAKE_SYSTEM_LIBRARY_PATH
    "${ARM_MSVC_ROOT}/lib/arm"
    "${ARM_SDK_ROOT}/Lib/${ARM_SDK_VERSION}/ucrt/arm"
    "${ARM_SDK_ROOT}/Lib/${ARM_SDK_VERSION}/um/arm")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
